[package]
name = "wlgopher"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
memmap2 = "0.9.4"
rand = "0.8.5"
tempfile = "3.10.1"
wayland-client = "0.31.3"
wayland-protocols = { version = "0.32.1", features = ["client"] }
